export const URL = 'https://localhost:3000/'
export const PUBLICATIONS_URL = 'https://localhost:3000/publications/'
export const USER_BASIC_INFO_URL = 'https://localhost:3000/users/userBasicInfo/'
export const PROFILE_URL = 'https://localhost:3000/profiles/'
export const USER_URL = 'https://localhost:3000/users/'
export const EXPERIENCE_URL = 'https://localhost:3000/experience/profile/'
export const EDUCATION_URL = 'https://localhost:3000/education/profile/'
export const RECOMMENDATION_URL = 'https://localhost:3000/recommendation/profile/'
export const CONNECTIONS_OF_AN_USER_URL = 'https://localhost:3000/connections/'
export const PUBLICATIONS_PROFILE_URL = 'https://localhost:3000/publications/user/'
export const ALL_USERS_URL = 'https://localhost:3000/users/'
export const REQUEST_URL = 'https://localhost:3000/connections/request/'
export const CREATE_EXPERIENCE_URL = 'https://localhost:3000/experience/'
export const CREATE_EDUCATION_URL = 'https://localhost:3000/education/'
export const UPDATE_USER_URL = "https://localhost:3000/users/update/"
export const PUBLICATIONS_COMMENTS_URL = 'https://localhost:3000/comments/'
export const PUBLICATIONS_LIKES_URL = 'https://localhost:3000/likes/'
export const MESSAGE_URL = 'https://localhost:3000/direct-messages/'
export const UPLOAD_IMAGE_URL = 'https://localhost:3000/profiles/upload/'


