export const PUBLICATIONS_URL = 'http://localhost:3000/publications/'
export const USER_BASIC_INFO_URL = 'http://localhost:3000/users/userBasicInfo/'
export const PROFILE_URL = 'http://localhost:3000/profiles/'
export const USER_URL = 'http://localhost:3000/users/'
export const EXPERIENCE_URL = 'http://localhost:3000/experience/profile/'
export const EDUCATION_URL = 'http://localhost:3000/education/profile/'
export const RECOMMENDATION_URL = 'http://localhost:3000/recommendation/profile/'
export const CONTACT_URL = 'http://localhost:3000/connections/'